### ISSUE TITLE
Add option to configure Timeouts

### ISSUE THREAD

**Issue by ANeumann82** [kudobuilder/test-tools#13]
Currently the timeouts for `instance.WaitForPlanComplete` and `instance.WaitForPlanDeploy` are fixed to 300 and 30 seconds.

There is one test that takes around 300 seconds:
```
[16:22:00][Step 5/7] • [SLOW TEST:299.554 seconds]
[16:22:00][Step 5/7] sanity-test Scales the instance's number of nodes 
```
and is therefore quite flaky, so we need to make these timeouts configurable.

**Comment by nfnt** [comment]
Agreed, while these functions should have default timeouts, one should be able to override them. As a workaround, you can use [WaitForPlanStatus](https://pkg.go.dev/github.com/kudobuilder/test-tools@v0.2.0/pkg/kudo?tab=doc#Instance.WaitForPlanStatus).
